//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dtxCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dtxCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License
        ///
        ///Copyright (c) 2011 Dtronix
        ///(http://dtronix.com/)
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &apos;Software&apos;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Licence_Dtronix_Core {
            get {
                return ResourceManager.GetString("Licence_Dtronix_Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License
        ///
        ///Copyright (c) 2006-2009 Stephen M. McKamey
        ///(http://jsonfx.net/)
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &apos;Software&apos;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following cond [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License_JsonFx_NET_JSON_Serializer {
            get {
                return ResourceManager.GetString("License_JsonFx_NET_JSON_Serializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7-Zip
        ///~~~~~
        ///License for use and distribution
        ///~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        ///7-Zip Copyright (C) 1999-2011 Igor Pavlov.
        ///(http://7-zip.org/)
        ///
        ///Licenses for files are:
        ///1) 7z.dll: GNU LGPL + unRAR restriction
        ///2) All other files:GNU LGPL
        ///
        ///The GNU LGPL + unRAR restriction means that you must follow both GNU LGPL rules and unRAR restriction rules.
        ///
        ///Note: 
        ///You can use 7-Zip on any computer, including a computer in a commercial organization. You don&apos;t need to register or pay for 7-Zip.
        ///
        ///GNU LGPL inf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License_Seven_Zip {
            get {
                return ResourceManager.GetString("License_Seven_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author     Joseph North
        ///Email      north@sublink.ca
        ///Website    http://sublink.ca/
        ///Copyright  (C) 2010 Joseph North. All rights reserved.
        ///
        ///Licence
        ///-------
        ///Creative Commons Attribution-ShareAlike 3.0 Unported
        ///
        ///You are free:
        ///
        ///to Share - to copy, distribute and transmit the work
        ///to Remix - to adapt the work
        ///
        ///Under the following conditions:
        ///
        ///Attribution.
        ///You must attribute the work in the manner specified by the author or licensor (but not in any way that suggests that they endorse you or your u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License_Sweetie_Icons {
            get {
                return ResourceManager.GetString("License_Sweetie_Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributed under the terms of the Code Project Open License (CPOL) 1.02 license:
        ///
        ///The License: http://www.codeproject.com/info/cpol10.aspx
        ///
        ///Thanks to P.J. van de Sande for this great class of code..
        /// </summary>
        internal static string License_ThrottledStream {
            get {
                return ResourceManager.GetString("License_ThrottledStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This File is Part of the CallButler Open Source PBX (http://www.codeplex.com/callbutler)
        ///
        ///Copyright (c) 2005-2008, Jim Heising
        ///All rights reserved.
        ///
        ///Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        ///
        ///Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        ///
        ///Redistributions in binary form must reproduce the above copyright notice, this list  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License_User_Activity_Hook {
            get {
                return ResourceManager.GetString("License_User_Activity_Hook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2009, wyDay
        ///All rights reserved.
        ///http://wyday.com/vistamenu/
        ///
        ///Redistribution and use in source and binary forms, with or without modification,are permitted provided that the following conditions are met: 
        ///Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        ///Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License_Vista_Menu {
            get {
                return ResourceManager.GetString("License_Vista_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Forgotten Gaming for beta testing and support.
        ///(http://nfgaming.com/)
        ///
        ///Mootools for inspiration in many programming strategies.
        ///(http://mootools.net/)
        ///
        ///Robert Penner for easing equations
        ///(http://www.robertpenner.com).
        /// </summary>
        internal static string Special_Thanks {
            get {
                return ResourceManager.GetString("Special_Thanks", resourceCulture);
            }
        }
    }
}
